
version: '3'

services:

  mongos:
    container_name: mongos
    image: img_mongo_ubt2004:latest
    command: mongos --configdb config_rs/configsvr1:27017,config_rs/configsvr2:27017,config_rs/configsvr3:27017 --port 27017
    ports:
      - 30000:27017

networks:
  default:
    name: ubt-mongo-bridge